#ifndef NESPROJECT_GATEAUTOOPENINGPROCESS_C_H
#define NESPROJECT_GATEAUTOOPENINGPROCESS_C_H

#include "contiki.h"

PROCESS_NAME(gateAutoOpeningProcess);

#endif //NESPROJECT_GATEAUTOOPENINGPROCESS_C_H
