#ifndef NESPROJECT_AVERAGETEMPERATUREPROCESS_H
#define NESPROJECT_AVERAGETEMPERATUREPROCESS_H

#include "contiki.h"

extern double averageTemperature;
PROCESS_NAME(averageTemperatureProcess);

#endif //NESPROJECT_AVERAGETEMPERATUREPROCESS_H
