//
// Created by enric on 27/10/2017.
//

#ifndef NESPROJECT_CONSTANTS_H
#define NESPROJECT_CONSTANTS_H

#define COMMANDS_NUMBER 5

#define ALARM_TOGGLE_COMMAND 1
#define GATELOCK_TOGGLE_COMMAND 2
#define DOORS_OPEN_COMMAND 3
#define AVERAGE_TEMPERATURE_COMMAND 4
#define LIGHT_VALUE_COMMAND 5

#define COMMAND_TIMEOUT 4
#define ALARM_LED_PERIOD 2

#endif //NESPROJECT_CONSTANTS_H
