PROJECT_SOURCEFILES += \
    addresses.c alarm_process.c cuRimeStack.c gateRimeStack.c \
    doorRimeStack.c averageTemperatureProcess.c doorAutoOpening.c

CONTIKI = ../contiki
CONTIKI_WITH_RIME = 1

CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

include $(CONTIKI)/Makefile.include
